name: Test

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Git User
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GoDaddy Git User
        uses: ./

      - name: Expect Git user to be GoDaddy
        run: |
          if [ "godaddy-wordpress-bot" != "$(git config user.name)" ]; then
            git config user.name
            exit 1
          fi
          if [ "plugins@godaddy.com" != "$(git config user.email)" ]; then
            git config user.email
            exit 1
          fi

